### PR TITLE
Refactored CLI

### PR DESCRIPTION
**Pull request by jjcollinge**

### CODE REVIEW

**Comment by jjcollinge** [comment]
Do not merge until agreed - potentially further work required

**Comment by cloudbeatsch** [comment]
@jjcollinge I followed the instructions of the README and got the following error when running
`lenis service list`

````
C:\repos\tmp\project-lenis\cli [cosmetic ≡ +0 ~2 -0 !]> lenis service list

C:\repos\tmp\project-lenis\cli\serviceHelper.js:123
            if (error) throw error;
                       ^
Error
    at Function.StorageServiceClient._normalizeError (C:\repos\tmp\project-lenis\cli\node_modules\azure-storage\lib\comm
on\services\storageserviceclient.js:1189:23)
    at TableService.StorageServiceClient._processResponse (C:\repos\tmp\project-lenis\cli\node_modules\azure-storage\lib
\common\services\storageserviceclient.js:736:50)
    at Request.processResponseCallback [as _callback] (C:\repos\tmp\project-lenis\cli\node_modules\azure-storage\lib\com
mon\services\storageserviceclient.js:311:37)
    at Request.self.callback (C:\repos\tmp\project-lenis\cli\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\repos\tmp\project-lenis\cli\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\repos\tmp\project-lenis\cli\node_modules\request\request.js:1091:12)
```

**Comment by jjcollinge** [comment]
Currently, when you deploy your function app via the CLI you occasionally get a 500 server timeout - the upload works as expected but not sure why the Kudu API returns the error. Needs further investigation.

**Comment by jjcollinge** [comment]
Closed in favour of #27

**Pull request closed without merging**
